/*********************************************************************
 * Class: CIST 2931 Advanced systems Project
 * Instructor: Dave Busse
 * Description: DeRiche agency
 * Date: <09/26/15>
 * @author <Sara_Aliaga&Aaron_Jones>
 * @version 1.0
 *
 * By turning in this code, I Pledge:
 *  1. That I have completed the programming assignment independently.
 *  2. I have not copied the code from a student or any source.
 *  3. I have not given my code to any student.
 *
 ************************************************************************/

package deriche_gui;

import Business.*;
import javax.swing.JOptionPane;

/*************************************************************
 * @author Sara
 *************************************************************/
public class AdminHome extends javax.swing.JFrame {

    /***********************************************************
     * Creates new form participant
     **********************************************************/
    public AdminHome() {
        initComponents();
    }

    /**********************************************************************
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     *************************************************************************/
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        CloseButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        ClearButton = new javax.swing.JButton();
        goalsButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lastNTxf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        idTxF = new javax.swing.JTextField();
        nameTxf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        selectButton = new javax.swing.JButton();
        insertB = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        empLnTxf = new javax.swing.JTextField();
        empFnTxf = new javax.swing.JTextField();
        empIdTxf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        findEmButton = new javax.swing.JButton();
        insertEmButton = new javax.swing.JButton();
        updateEmButton = new javax.swing.JButton();
        deleteEmButton = new javax.swing.JButton();
        empPswTxf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        empCombobox = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        mainButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        creategB = new javax.swing.JButton();
        findgB = new javax.swing.JButton();
        gidTxf = new javax.swing.JTextField();
        deletegB = new javax.swing.JButton();
        editgB = new javax.swing.JButton();
        gdTxf = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        oiTxf = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        findObjButton = new javax.swing.JButton();
        createObutton = new javax.swing.JButton();
        upbutton = new javax.swing.JButton();
        deleteOjButton = new javax.swing.JButton();
        odescTxf = new javax.swing.JTextField();
        goalidTxf = new javax.swing.JTextField();
        timeWtxf = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        goalsMenuItem = new javax.swing.JMenuItem();
        addnoteItemMenu = new javax.swing.JMenuItem();
        reviewNoteImenu = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        mainPMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        clearMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrator Form");

        CloseButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        CloseButton.setForeground(new java.awt.Color(204, 0, 0));
        CloseButton.setText("Close");
        CloseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseButtonMouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deriche_gui/Derichelogo.png"))); // NOI18N
        jLabel5.setBorder(new javax.swing.border.MatteBorder(null));

        ClearButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ClearButton.setForeground(new java.awt.Color(0, 153, 153));
        ClearButton.setText("Clear");
        ClearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClearButtonMouseClicked(evt);
            }
        });
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        goalsButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        goalsButton.setForeground(new java.awt.Color(0, 153, 0));
        goalsButton.setText("Goals");
        goalsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goalsButtonMouseClicked(evt);
            }
        });
        goalsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goalsButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 153));
        jLabel1.setText("DeRiche Agency ");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Participant", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 14), new java.awt.Color(204, 0, 51))); // NOI18N

        lastNTxf.setForeground(new java.awt.Color(51, 51, 255));
        lastNTxf.setBorder(null);
        lastNTxf.setPreferredSize(new java.awt.Dimension(6, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Name:");

        idTxF.setForeground(new java.awt.Color(51, 51, 255));
        idTxF.setBorder(null);
        idTxF.setPreferredSize(new java.awt.Dimension(6, 20));

        nameTxf.setForeground(new java.awt.Color(51, 51, 255));
        nameTxf.setBorder(null);
        nameTxf.setPreferredSize(new java.awt.Dimension(6, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Participant ID:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Last Name:");

        selectButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        selectButton.setForeground(new java.awt.Color(0, 153, 0));
        selectButton.setText("Select");
        selectButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectButtonMouseClicked(evt);
            }
        });
        selectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectButtonActionPerformed(evt);
            }
        });

        insertB.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        insertB.setForeground(new java.awt.Color(0, 153, 0));
        insertB.setText("Insert");
        insertB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertBActionPerformed(evt);
            }
        });

        editButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        editButton.setForeground(new java.awt.Color(0, 153, 0));
        editButton.setText("Update");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(0, 153, 0));
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lastNTxf, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(nameTxf, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(idTxF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(selectButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(insertB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton)
                        .addGap(0, 12, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idTxF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTxf, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(lastNTxf, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton)
                    .addComponent(editButton)
                    .addComponent(insertB)
                    .addComponent(selectButton))
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Employee", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 14), new java.awt.Color(204, 0, 0))); // NOI18N

        empLnTxf.setBorder(null);

        empFnTxf.setBorder(null);

        empIdTxf.setBorder(null);
        empIdTxf.setPreferredSize(new java.awt.Dimension(6, 24));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 255));
        jLabel6.setText("Employee ID:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("Last Name:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("First Name:");

        findEmButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        findEmButton.setForeground(new java.awt.Color(0, 153, 0));
        findEmButton.setText("Select");
        findEmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findEmButtonActionPerformed(evt);
            }
        });

        insertEmButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        insertEmButton.setForeground(new java.awt.Color(0, 153, 0));
        insertEmButton.setText("Insert");
        insertEmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertEmButtonActionPerformed(evt);
            }
        });

        updateEmButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        updateEmButton.setForeground(new java.awt.Color(0, 153, 0));
        updateEmButton.setText("Update");
        updateEmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEmButtonActionPerformed(evt);
            }
        });

        deleteEmButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        deleteEmButton.setForeground(new java.awt.Color(0, 153, 0));
        deleteEmButton.setText("Delete");
        deleteEmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEmButtonActionPerformed(evt);
            }
        });

        empPswTxf.setBorder(null);
        empPswTxf.setPreferredSize(new java.awt.Dimension(6, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 0, 255));
        jLabel9.setText("Password");

        empCombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "admin", "employee", "guest", "reviewer" }));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 255));
        jLabel15.setText("Level:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(findEmButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(insertEmButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateEmButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteEmButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(42, 42, 42))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(empIdTxf, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(empPswTxf, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                        .addComponent(empFnTxf)
                                        .addComponent(empLnTxf))
                                    .addComponent(empCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(empIdTxf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empPswTxf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empFnTxf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(empLnTxf, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findEmButton)
                    .addComponent(insertEmButton)
                    .addComponent(updateEmButton)
                    .addComponent(deleteEmButton))
                .addContainerGap())
        );

        mainButton.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        mainButton.setForeground(new java.awt.Color(0, 0, 153));
        mainButton.setText("Back to main");
        mainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainButtonActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Goals", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 14), new java.awt.Color(204, 0, 51))); // NOI18N

        jLabel11.setText("Description:");

        jLabel10.setText("Goals ID:");

        creategB.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        creategB.setForeground(new java.awt.Color(0, 153, 0));
        creategB.setText("Create");
        creategB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creategBActionPerformed(evt);
            }
        });

        findgB.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        findgB.setForeground(new java.awt.Color(0, 153, 0));
        findgB.setText("Find");
        findgB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findgBActionPerformed(evt);
            }
        });

        deletegB.setText("Delete");
        deletegB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletegBActionPerformed(evt);
            }
        });

        editgB.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        editgB.setForeground(new java.awt.Color(0, 153, 0));
        editgB.setText("Update");
        editgB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editgBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(32, 32, 32)
                        .addComponent(gidTxf, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(findgB))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(creategB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editgB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deletegB))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(gdTxf, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(gidTxf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(findgB, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(gdTxf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creategB)
                    .addComponent(editgB)
                    .addComponent(deletegB))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Objectives", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 14), new java.awt.Color(204, 0, 0))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 255));
        jLabel13.setText("Description:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 255));
        jLabel12.setText("Objective ID:");

        findObjButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        findObjButton.setForeground(new java.awt.Color(0, 153, 0));
        findObjButton.setText("Select");
        findObjButton.setToolTipText("");
        findObjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findObjButtonActionPerformed(evt);
            }
        });

        createObutton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        createObutton.setForeground(new java.awt.Color(0, 153, 0));
        createObutton.setText("Create");
        createObutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createObuttonActionPerformed(evt);
            }
        });

        upbutton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        upbutton.setForeground(new java.awt.Color(0, 153, 0));
        upbutton.setText("Update");
        upbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upbuttonActionPerformed(evt);
            }
        });

        deleteOjButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        deleteOjButton.setForeground(new java.awt.Color(0, 153, 0));
        deleteOjButton.setText("Delete");
        deleteOjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteOjButtonActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 255));
        jLabel17.setText("Goal ID:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 255));
        jLabel18.setText("Max Times Worked:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addGap(85, 85, 85)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(odescTxf)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(oiTxf, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(goalidTxf)
                            .addComponent(timeWtxf)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 8, Short.MAX_VALUE)
                        .addComponent(findObjButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(createObutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(upbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteOjButton)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(oiTxf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(odescTxf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(goalidTxf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeWtxf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteOjButton)
                    .addComponent(upbutton)
                    .addComponent(createObutton)
                    .addComponent(findObjButton))
                .addContainerGap())
        );

        jMenu1.setText("File");

        goalsMenuItem.setText("AddGoals");
        goalsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goalsMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(goalsMenuItem);

        addnoteItemMenu.setText("Add note");
        addnoteItemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addnoteItemMenuActionPerformed(evt);
            }
        });
        jMenu1.add(addnoteItemMenu);

        reviewNoteImenu.setText("Review Note");
        reviewNoteImenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reviewNoteImenuActionPerformed(evt);
            }
        });
        jMenu1.add(reviewNoteImenu);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Participant");
        jMenu1.add(jCheckBoxMenuItem1);

        mainPMenuItem.setText("Log out");
        mainPMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainPMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(mainPMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        clearMenuItem.setText("Clear");
        clearMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(clearMenuItem);

        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(exitMenuItem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(ClearButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CloseButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(goalsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mainButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(38, 38, 38)
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ClearButton)
                        .addComponent(CloseButton)
                        .addComponent(goalsButton))
                    .addComponent(mainButton))
                .addGap(154, 154, 154))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClearButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearButtonMouseClicked
        // TODO add your handling code here:
        
         idTxF.setText(null);
         nameTxf.setText(null);
         lastNTxf.setText(null);
         empIdTxf.setText(null);
         empFnTxf.setText(null);
         empLnTxf.setText(null);
         empPswTxf.setText(null);
         gidTxf.setText(null);
         gdTxf.setText(null);
         oiTxf.setText(null);
         odescTxf.setText(null);
         goalidTxf.setText(null);
         timeWtxf.setText(null);
         
    }//GEN-LAST:event_ClearButtonMouseClicked

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void CloseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseButtonMouseClicked
        // TODO add your handling code here:
        
        int jmiExit = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit? ", "Exit", JOptionPane.YES_NO_OPTION);  
            if (jmiExit==0){    
     System.exit(0);
            }
    }//GEN-LAST:event_CloseButtonMouseClicked

    private void goalsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goalsButtonMouseClicked
        
        
       /*  adminGUIForm lg = new adminGUIForm();
         lg.setVisible(true);*/
    }//GEN-LAST:event_goalsButtonMouseClicked

    private void selectButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectButtonMouseClicked
        // TODO add your handling code here:
       
        String pid = idTxF.getText();
        
        Participant p1 = new Participant();
        p1.selectDB(pid);
        p1.display();
        nameTxf.setText(p1.getFname());
        lastNTxf.setText(p1.getLname());
       
    }//GEN-LAST:event_selectButtonMouseClicked

    private void insertBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertBActionPerformed
        // TODO add your handling code here:
        try{
        String pin = idTxF.getText();
        String pn = nameTxf.getText();
        String ln= lastNTxf.getText();
        
        Participant p2 = new Participant();
        p2.insertDB(pin, pn, ln);
        p2.display();
            JOptionPane.showMessageDialog(null, " new participant sucessfully inserted ");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, " insert information to add ");
        }
        
        
        
        
    }//GEN-LAST:event_insertBActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        try{
        String pin = idTxF.getText();
        String pn = nameTxf.getText();
        String ln= lastNTxf.getText();
        
        Participant p3 = new Participant();
        p3.selectDB(pin);
        p3.setId(pin);
        p3.setFname(pn);
        p3.setLname(ln);
        p3.updateDB();
        JOptionPane.showMessageDialog(null, "Information Updated");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, " information not Updated ");
        }
        
    }//GEN-LAST:event_editButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        
        try{
        String pd = idTxF.getText();
        //String pg;
        
        Participant p4 = new Participant();
        p4.selectDB(pd);
        
        int pdelete = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this goal? ", "Deleted!", JOptionPane.YES_NO_OPTION);
                    if(pdelete == 0){
                        p4.deleteDB();
                        JOptionPane.showMessageDialog(null, " Participant successfully deleted! ");
                    }else{
                        JOptionPane.showMessageDialog(null, " Participant not deleted! ");
                    }             
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, " Participant not delete ");
        }
        
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void findEmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findEmButtonActionPerformed
        // TODO add your handling code here:
        try{
            String pid = empIdTxf.getText();
        
        User p1 = new User();
        p1.selectDB(pid);
        p1.display();
        empPswTxf.setText(p1.getPassword());
        empFnTxf.setText(p1.getFname());
        empLnTxf.setText(p1.getLname());
        empCombobox.setSelectedItem(p1.getLevel());
        }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
               // JOptionPane.showMessageDialog(null, " Participant successfully deleted! ");
        }
        
    }//GEN-LAST:event_findEmButtonActionPerformed

    private void insertEmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertEmButtonActionPerformed
        // TODO add your handling code here:
        
        try{
        String ein = empIdTxf.getText();
        String epss = empPswTxf.getText();
        String en = empFnTxf.getText();
        String ln= empLnTxf.getText();
        
        User p2 = new User();
        p2.insertDB(ein, epss, en, ln, empCombobox.getSelectedItem().toString());
       
        p2.display();
            JOptionPane.showMessageDialog(null, " new user sucessfully inserted ");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, " insert information to add ");
        }
    }//GEN-LAST:event_insertEmButtonActionPerformed

    private void updateEmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEmButtonActionPerformed
        // TODO add your handling code here:
        try{
        String ein = empIdTxf.getText();
        String psw = empPswTxf.getText();
        String en = empFnTxf.getText();
        String ln= empLnTxf.getText();
        String lv = empCombobox.getSelectedItem().toString(); 
        
        
       User u1 = new User();
       u1.selectDB(ein);
       u1.setId(ein);
       u1.setPassword(psw);
       u1.setFname(en);
       u1.setLname(ln);
       u1.setLevel(lv);
       u1.updateDB();
            JOptionPane.showMessageDialog(null, " information Updated! ");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, " information not Updated ");
        }
        
        
    }//GEN-LAST:event_updateEmButtonActionPerformed

    private void deleteEmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEmButtonActionPerformed
        // TODO add your handling code here:
        
        /*
        
         if(gdelete == 0){
                        p4.deleteDB();
                        JOptionPane.showMessageDialog(null, " Participant successfully deleted! ");
                    }else{
                        JOptionPane.showMessageDialog(null, " Participant not deleted! ");
                    }        
        */
        
        
        try{
            
            String eid = empIdTxf.getText();
            User u3 = new User();
            u3.selectDB(eid);
           int delete = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete? ", "Deleted!", JOptionPane.YES_NO_OPTION);
            if(delete == 0){
                u3.deleteDB();
                JOptionPane.showMessageDialog(null, "Successfully Deleted! ");
            }else{
                    JOptionPane.showMessageDialog(null, "Employee not Deleted! ");
            }
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Unsuccessfully Deleted! ");
        }
        
    }//GEN-LAST:event_deleteEmButtonActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        // TODO add your handling code here:
        int jmiExit = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit? ", "Exit", JOptionPane.YES_NO_OPTION);  
            if (jmiExit==0){    
     System.exit(0);
            }
        
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void clearMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearMenuItemActionPerformed
        // TODO add your handling code here:
        
         idTxF.setText(null);
         nameTxf.setText(null);
         lastNTxf.setText(null);
         empIdTxf.setText(null);
         empFnTxf.setText(null);
         empLnTxf.setText(null);
         empPswTxf.setText(null);
        
    }//GEN-LAST:event_clearMenuItemActionPerformed

    private void mainPMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainPMenuItemActionPerformed
        // TODO add your handling code here:
        Login lg = new Login();
        lg.setVisible(true);
        this.setVisible(false);
       
    }//GEN-LAST:event_mainPMenuItemActionPerformed

    private void goalsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goalsMenuItemActionPerformed
        // TODO add your handling code here:
        goalsDisplay gd =new goalsDisplay();
        gd.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_goalsMenuItemActionPerformed

    private void goalsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goalsButtonActionPerformed
        // TODO add your handling code here:
        goalsDisplay gd = new goalsDisplay();
        gd.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_goalsButtonActionPerformed

    private void selectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectButtonActionPerformed

    private void findgBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findgBActionPerformed
        // TODO add your handling code here:
        
         try{
           String ig = gidTxf.getText();
            Goal g = new Goal(); 
            g.selectDB(ig);
            g.display();
            gidTxf.setText(g.getId());
            gdTxf.setText(g.getDescription());
        }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
               // JOptionPane.showMessageDialog(null, " Participant successfully deleted! ");
        }
    }//GEN-LAST:event_findgBActionPerformed

    private void creategBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creategBActionPerformed
        // TODO add your handling code here:
        try{
            String ig = gidTxf.getText();
            String gd = gdTxf.getText();
            Goal g1 = new Goal();
            g1.insertDB(ig, gd);
            JOptionPane.showMessageDialog(null, " new goal sucessfully inserted ");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, " insert information to add ");
        }
        
    }//GEN-LAST:event_creategBActionPerformed

    private void editgBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editgBActionPerformed
        // TODO add your handling code here:
        try{
        String ig = gidTxf.getText();
        String gd = gdTxf.getText();
        Goal g2 = new Goal();
        g2.selectDB(ig);
        g2.setId(ig);
        g2.setDescription(gd);
        g2.updateDB();
            JOptionPane.showMessageDialog(null, "sucessfully updated");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "information not Updated");
        }
    }//GEN-LAST:event_editgBActionPerformed

    private void deletegBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletegBActionPerformed
        // TODO add your handling code here:
        try{
            String ig = gidTxf.getText();
            Goal g3 = new Goal();
            g3.selectDB(ig);
                int gdelete = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this goal? ", "Deleted!", JOptionPane.YES_NO_OPTION);
                    if(gdelete == 0){
                g3.deleteDB();
                JOptionPane.showMessageDialog(null, "goal Deleted!");
                    }else{
                JOptionPane.showMessageDialog(null, "goal not deleted");
                    }
        }catch(Exception e){
                JOptionPane.showMessageDialog(null, "goal not deleted");
        }
    }//GEN-LAST:event_deletegBActionPerformed

    private void createObuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createObuttonActionPerformed
        //insert objective
        try{
            String oi = oiTxf.getText();
            String od = odescTxf.getText();
            String gid = goalidTxf.getText();
            String tw = timeWtxf.getText();
            int t = Integer.parseInt(tw);
            Objective o2 = new Objective();
            
            
            o2.insertDB(oi, gid, od, 0, t);
            JOptionPane.showMessageDialog(null, "new objective inserted");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "objective not inserted");
        }
        
    }//GEN-LAST:event_createObuttonActionPerformed

    private void findObjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findObjButtonActionPerformed
        // TODO add your handling code here:
        try{
           String io = oiTxf.getText();
            Objective o = new Objective(); 
            o.selectDB(io);
            o.display();
            oiTxf.setText(o.getIdo());
            odescTxf.setText(o.getDescription());
            goalidTxf.setText(o.getIdg());
            
            timeWtxf.setText(o.getMax()+"");
        }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
               // JOptionPane.showMessageDialog(null, " Participant successfully deleted! ");
        }
    }//GEN-LAST:event_findObjButtonActionPerformed

    private void upbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upbuttonActionPerformed
        // TODO add your handling code here:
        try{
            String oi = oiTxf.getText();
            String od = odescTxf.getText();
            String gi = goalidTxf.getText();
            String tw = timeWtxf.getText();
            int t = Integer.parseInt(tw);
            
            Objective o3 = new Objective();
            o3.selectDB(oi);
            o3.setIdo(oi);
            o3.setTimesWorked(00);
             o3.setDescription(od);
             o3.setIdg(gi);
            o3.setMax(t);
            o3.updateDB();
            JOptionPane.showMessageDialog(null, "objective updated");
        }catch(Exception e){
              JOptionPane.showMessageDialog(null, "objective not inserted");  
                }
        
    }//GEN-LAST:event_upbuttonActionPerformed

    private void deleteOjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteOjButtonActionPerformed
        // TODO add your handling code here:
        
        try{
            String oid = oiTxf.getText();
            Objective o4 = new Objective();
            o4.selectDB(oid); 
           int odelete = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete? ", "Deleted!", JOptionPane.YES_NO_OPTION);
           if(odelete == 0){
               o4.deleteDB();
               JOptionPane.showMessageDialog(null, "Successfully Deleted! ");
           } else{
                JOptionPane.showMessageDialog(null, "Objective no Deleted! ");   
           }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "goal not deleted");
        }
    }//GEN-LAST:event_deleteOjButtonActionPerformed

    private void mainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainButtonActionPerformed
        // TODO add your handling code here:
        Login bi = new Login();
        bi.setVisible(true);
    }//GEN-LAST:event_mainButtonActionPerformed

    private void addnoteItemMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addnoteItemMenuActionPerformed
        // TODO add your handling code here:
        AddNote p1 = new AddNote();
        p1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_addnoteItemMenuActionPerformed

    private void reviewNoteImenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reviewNoteImenuActionPerformed
        // TODO add your handling code here:
        
        ReviewerLookup look = new ReviewerLookup();
        look.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_reviewNoteImenuActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton CloseButton;
    private javax.swing.JMenuItem addnoteItemMenu;
    private javax.swing.JMenuItem clearMenuItem;
    private javax.swing.JButton createObutton;
    private javax.swing.JButton creategB;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton deleteEmButton;
    private javax.swing.JButton deleteOjButton;
    private javax.swing.JButton deletegB;
    private javax.swing.JButton editButton;
    private javax.swing.JButton editgB;
    private javax.swing.JComboBox empCombobox;
    private javax.swing.JTextField empFnTxf;
    private javax.swing.JTextField empIdTxf;
    private javax.swing.JTextField empLnTxf;
    private javax.swing.JTextField empPswTxf;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JButton findEmButton;
    private javax.swing.JButton findObjButton;
    private javax.swing.JButton findgB;
    private javax.swing.JTextField gdTxf;
    private javax.swing.JTextField gidTxf;
    private javax.swing.JTextField goalidTxf;
    private javax.swing.JButton goalsButton;
    private javax.swing.JMenuItem goalsMenuItem;
    private javax.swing.JTextField idTxF;
    private javax.swing.JButton insertB;
    private javax.swing.JButton insertEmButton;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField lastNTxf;
    private javax.swing.JButton mainButton;
    private javax.swing.JMenuItem mainPMenuItem;
    private javax.swing.JTextField nameTxf;
    private javax.swing.JTextField odescTxf;
    private javax.swing.JTextField oiTxf;
    private javax.swing.JMenuItem reviewNoteImenu;
    private javax.swing.JButton selectButton;
    private javax.swing.JTextField timeWtxf;
    private javax.swing.JButton upbutton;
    private javax.swing.JButton updateEmButton;
    // End of variables declaration//GEN-END:variables
}
