/*********************************************************************
 * Class: CIST 2931 Advanced systems Project
 * Instructor: Dave Busse
 * Description: DeRiche agency
 * Date: <09/26/15>
 * @author <Sara_Aliaga>
 * @version 1.0
 *
 * By turning in this code, I Pledge:
 *  1. That I have completed the programming assignment independently.
 *  2. I have not copied the code from a student or any source.
 *  3. I have not given my code to any student.
 *
 ************************************************************************/

package deriche_gui;
import Business.*;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*************************************************************************
 * @author Sara
 ************************************************************************/
public class goalsDisplay extends javax.swing.JFrame {

    /**********************************************
     * Creates new form goalsDisplay
     *********************************************/
    public goalsDisplay() {
        initComponents();
    }

    /************************************************************************
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     **********************************************************************/
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        idgTxf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        findButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        descGTxf = new javax.swing.JTextField();
        clearButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displaytxa = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        idgoalTxf = new javax.swing.JTextField();
        idptxf = new javax.swing.JTextField();
        deleteGoal = new javax.swing.JButton();
        addGoal = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        administratorMenuItem = new javax.swing.JMenuItem();
        editMenuItem = new javax.swing.JMenuItem();
        reviewNoteMenuItem = new javax.swing.JMenuItem();
        logOutMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        clearMemuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add and Delete Goals and Objectives");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deriche_gui/Derichelogo.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 204));
        jLabel6.setText("DeRiche Agency");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Goals:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 14), new java.awt.Color(255, 0, 0))); // NOI18N

        jLabel1.setText("Goal ID:");

        findButton.setBackground(new java.awt.Color(0, 153, 0));
        findButton.setText("Find");
        findButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                findButtonMouseClicked(evt);
            }
        });
        findButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Description:");

        clearButton.setBackground(new java.awt.Color(0, 0, 153));
        clearButton.setText("Clear Text Field");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        displaytxa.setColumns(20);
        displaytxa.setRows(5);
        jScrollPane1.setViewportView(displaytxa);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(clearButton)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(idgTxf, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(findButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 110, Short.MAX_VALUE))
                            .addComponent(descGTxf)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findButton)
                    .addComponent(idgTxf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descGTxf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clearButton)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add / Delete Goals from Participant", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 14), new java.awt.Color(204, 0, 0))); // NOI18N

        deleteGoal.setBackground(new java.awt.Color(255, 51, 51));
        deleteGoal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        deleteGoal.setText("Delete Goal");
        deleteGoal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteGoalActionPerformed(evt);
            }
        });

        addGoal.setBackground(new java.awt.Color(0, 153, 0));
        addGoal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addGoal.setText("Add goal");
        addGoal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGoalActionPerformed(evt);
            }
        });

        jLabel8.setText("Participant ID:");

        jLabel9.setText("Goal ID:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idptxf, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(35, 35, 35)
                        .addComponent(idgoalTxf, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(addGoal, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteGoal, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idptxf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idgoalTxf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addGoal)
                    .addComponent(deleteGoal))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        administratorMenuItem.setText("AdminForm");
        administratorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                administratorMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(administratorMenuItem);

        editMenuItem.setText("Add Note");
        editMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(editMenuItem);

        reviewNoteMenuItem.setText("ReviewNotes");
        reviewNoteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reviewNoteMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(reviewNoteMenuItem);

        logOutMenuItem.setText("Log out");
        logOutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(logOutMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        clearMemuItem.setText("Clear");
        clearMemuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearMemuItemActionPerformed(evt);
            }
        });
        jMenu2.add(clearMemuItem);

        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(exitMenuItem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2)
                        .addGap(161, 161, 161)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel6)
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void findButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_findButtonMouseClicked
      
    }//GEN-LAST:event_findButtonMouseClicked

    private void findButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findButtonActionPerformed
       
        String ig = idgTxf.getText();
        //String ds = descGTxf.getText();
        Goal g = new Goal(); 
        StringBuffer str1 = new StringBuffer();
        g.selectDB(ig);
        g.display();
        idgTxf.setText(g.getId());
        descGTxf.setText(g.getDescription());
        
        for(Objective o1:g.go.go){
                str1.append(o1.objectiveDetails()+"\n");
        }
        displaytxa.setText(str1.toString());
        
       // goalsComboBox.add(this);
      
    }//GEN-LAST:event_findButtonActionPerformed
        DefaultListModel model = new DefaultListModel();
    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        idgTxf.setText(null);
        descGTxf.setText(null);
        displaytxa.setText(null);
        idptxf.setText(null);
        idgoalTxf.setText(null);
    }//GEN-LAST:event_clearButtonActionPerformed

    
    private void addGoalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGoalActionPerformed
       
        try{
            String pg = idptxf.getText();
            String ig = idgoalTxf.getText();
            
            Participant p1 =new Participant();
            Goal g1 = new Goal(ig);
            p1.setId(pg);
            p1.addGoal(g1);
            JOptionPane.showMessageDialog(null, "Goal added");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Goal not added");
        }
    }//GEN-LAST:event_addGoalActionPerformed

    private void deleteGoalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteGoalActionPerformed
        // TODO add your handling code here:
        try{
            String pg = idptxf.getText();
            String ig = idgoalTxf.getText();
            
            Participant p1 =new Participant(pg);
            Goal g1 = new Goal(ig);
            p1.getId();
            
            int deleteG = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete? ", "Deleted!", JOptionPane.YES_NO_OPTION);
             if(deleteG == JOptionPane.YES_OPTION){
              //p1.deleteDB();
              p1.delGoal(g1); 
            JOptionPane.showMessageDialog(null, "Successfully Deleted! ");
             }else{
             JOptionPane.showMessageDialog(null, "Goal not Deleted! ");
             }   
        }catch(Exception e){
            
             JOptionPane.showMessageDialog(null, "Goal not ddleted!");
        }
        
    }//GEN-LAST:event_deleteGoalActionPerformed

    private void clearMemuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearMemuItemActionPerformed
        // TODO add your handling code here:
        
        idgTxf.setText(null);
        descGTxf.setText(null);
        idptxf.setText(null);
        idgoalTxf.setText(null);
        
        
    }//GEN-LAST:event_clearMemuItemActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        // TODO add your handling code here:
        int jmiExit = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit? ", "Exit", JOptionPane.YES_NO_OPTION);  
            if (jmiExit==0){    
     System.exit(0);
            }
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void administratorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_administratorMenuItemActionPerformed
        // TODO add your handling code here:
        try{
            AdminHome p1 = new AdminHome();
            p1.setVisible(true);
        }catch(Exception ex){}
        JOptionPane.showMessageDialog(null, "Objective not deleted!");
    }//GEN-LAST:event_administratorMenuItemActionPerformed

    private void editMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMenuItemActionPerformed
        // TODO add your handling code here:
        AddNote pi1 = new AddNote();
            pi1.setVisible(true);
    }//GEN-LAST:event_editMenuItemActionPerformed

    private void reviewNoteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reviewNoteMenuItemActionPerformed
        // TODO add your handling code here:
        ReviewerLookup look = new ReviewerLookup(); 
        look.setVisible(true);

    }//GEN-LAST:event_reviewNoteMenuItemActionPerformed

    private void logOutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutMenuItemActionPerformed
        // TODO add your handling code here:
        Login lg = new Login();
        lg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logOutMenuItemActionPerformed

    /**********************************************************
     * @param args the command line arguments
     *********************************************************/
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(goalsDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(goalsDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(goalsDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(goalsDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new goalsDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addGoal;
    private javax.swing.JMenuItem administratorMenuItem;
    private javax.swing.JButton clearButton;
    private javax.swing.JMenuItem clearMemuItem;
    private javax.swing.JButton deleteGoal;
    private javax.swing.JTextField descGTxf;
    private javax.swing.JTextArea displaytxa;
    private javax.swing.JMenuItem editMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JButton findButton;
    private javax.swing.JTextField idgTxf;
    private javax.swing.JTextField idgoalTxf;
    private javax.swing.JTextField idptxf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem logOutMenuItem;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JMenuItem reviewNoteMenuItem;
    // End of variables declaration//GEN-END:variables
}
